name: Airthings
version: 1.2.0
slug: airthings
description: Read sensor values from Airthings Wave environmental monitoring devices
url: https://github.com/mjmccans/hassio-addon-airthings
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
host_dbus: "true"
services:
  - mqtt:need
options:
  devices:
    - mac: ""
      name: ""
  refresh_interval: 150
  retry_count: 10
  retry_wait: 3
  log_level: INFO
  mqtt_discovery: true
  retain: false
schema:
  devices:
    - mac: str?
      name: str?
  refresh_interval: int
  retry_count: int
  retry_wait: int
  log_level: list(CRITICAL|ERROR|WARNING|INFO|DEBUG)
  mqtt_discovery: bool
  retain: bool?
  mqtt_host: str?
  mqtt_port: int?
  mqtt_username: str?
  mqtt_password: str?
# image: mjmccans/hassio-addon-airthings-{arch}
