# Set out mac addresses for Airthings devices to use. If you have multiple
# devices you can set out multiple [[devices]] blocks each with "mac" set. Each
# device can then have various sensors associated with it, and you can set out
# the values for each sensor that will be sent to Home Assistant through mqtt
# discovery.
#
# If you want to discover your devices, comment out the [[devices]] block and
# then when you run the script it will first try searching for Airthings
# devices. Note that it can take a few tries to find a device, so keep an eye
# on the output from the script and run it a few times.
#
# See https://www.home-assistant.io/integrations/sensor and the rest of the
# Home Assistant documentation for what attributes can be set for these sensors.

[[devices]]
mac = "58:93:D8:8B:12:7C"
    [devices.radon_1day_avg]
        name = "Basement Office Radon (1 day avg.)"
        unit_of_measurement = "Bq/m3"
        icon = "mdi:radioactive"
    [devices.radon_longterm_avg]
        name = "Basement Office Radon (longterm avg.)"
        unit_of_measurement = "Bq/m3"
        icon = "mdi:radioactive"
    [devices.co2]
        name = "Basement Office CO2"
        unit_of_measurement = "ppm"
        icon = "mdi:molecule-co2"
    [devices.voc]
        name = "Basement Office VOC"
        unit_of_measurement = "ppb"
        icon = "mdi:cloud"
    [devices.temperature]
        name = "Basement Office Temperature"
        device_class = "temperature"
        unit_of_measurement = "°C"
    [devices.humidity]
        name = "Basement Office Humidity"
        device_class = "humidity"
        unit_of_measurement = "%"
    [devices.rel_atm_pressure]
        name = "Basement Office Pressure"
        device_class = "pressure"
        unit_of_measurement = "mbar"


# Configure your mqtt broker information. At a minimum you need to include host
# (which can be an ip address or a name resolved through dns) and port. If
# a username is set also set a password.

[mqtt]
host = "hass"
port = 1883
username = "NONE"
password = "NONE"


# General configuration for the airthings-mqtt-ha Python script.

[general]
# How many seconds to wait before next refresh. Note that the sensors on the
# Airthings Wave + only update every 5 minutes, but this has been set to half
# that to avoid delays in getting new sensor values.
refresh_interval = 150

# Number of times to retry when there is a bluetooth error befor exiting.
retry_count = 10

# Time to wait between reties in seconds.
retry_wait = 3

# Logging Level (must be one of "CRITICAL", "ERROR", "WARNING", "INFO" or
# "DEBUG")
log_level = "INFO"
#log_level = "ERROR"

